steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - artifacts/records-request-worker/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/legacy-design-tools-prod/apps/records-request-worker:p85-v18
      - -t
      - us-central1-docker.pkg.dev/legacy-design-tools-prod/apps/records-request-worker:latest
      - .
images:
  - us-central1-docker.pkg.dev/legacy-design-tools-prod/apps/records-request-worker:p85-v18
  - us-central1-docker.pkg.dev/legacy-design-tools-prod/apps/records-request-worker:latest
