import type { PublisherIntakeRoomRow } from "./types";

export const PUBLISHER_PLAN_TYPES = [
  { id: "single_family", label: "Single Family Plan" },
  { id: "multi_family", label: "Multi Family Plan" },
  { id: "duplex", label: "Duplex Plan" },
  { id: "garage", label: "Garage Plan" },
] as const;

export const PUBLISHER_STORY_OPTIONS = [
  { id: "1", label: "1 Story" },
  { id: "1.5", label: "1-1/2 Story" },
  { id: "2", label: "2 Story" },
  { id: "3", label: "3 Story" },
] as const;

export const PUBLISHER_GARAGE_TYPES = [
  "Carport",
  "Courtyard Entry",
  "Detached",
  "Drive Under",
  "Front Entry",
  "Rear Entry",
  "Side Entry",
] as const;

export const PUBLISHER_PORCH_TYPES = [
  "Front",
  "Rear",
  "Screened",
  "Stacked",
  "Wrap Around",
] as const;

export const PUBLISHER_FOUNDATIONS = [
  "Crawl",
  "Finished Basement",
  "Unfinished Basement",
  "Pier",
  "Slab",
] as const;

export const PUBLISHER_ARCHITECTURAL_STYLES = [
  "Bungalow",
  "Colonial",
  "Early American",
  "Greek Revival",
  "Mountain",
  "Southwestern",
  "Cabin",
  "Contemporary",
  "European",
  "Historical",
  "Narrow Lot",
  "Split Foyer",
  "Cape Cod",
  "Cottage",
  "Farm House",
  "Lake Front",
  "Northwest",
  "Traditional",
  "Charleston",
  "Country",
  "Florida",
  "Log",
  "Prairie",
  "Tudor",
  "Classical",
  "Craftsman",
  "French Country",
  "Luxury",
  "Ranch",
  "Vacation",
  "Coastal",
  "Custom",
  "Georgian",
  "Mediterranean",
  "Southern",
  "Victorian",
] as const;

export const PUBLISHER_PLAN_FEATURES = [
  "Additional Bedroom Down",
  "Keeping Room",
  "Mother-in-Law Suite",
  "Bonus Room",
  "Laundry Lower Level",
  "Mud Room",
  "Computer Room",
  "Laundry on Main Floor",
  "Music Room",
  "Elevator",
  "Laundry on second floor",
  "Nook",
  "Exercise Room",
  "Library",
  "Sitting Room",
  "Formal Living Room",
  "Loft",
  "Split Bedrooms",
  "Guest Room",
  "Master on Main",
  "Study",
  "Home Office",
  "Master Up",
  "Sun Room",
  "Jack and Jill Bathroom",
  "Media Room",
  "Two Masters",
] as const;

export const PUBLISHER_PLAN_PRODUCTS = [
  "1 Set of Plans",
  "4 Sets of Plans",
  "5 Sets of Plans",
  "6 Sets of Plans",
  "8 Sets of Plans",
  "9 Sets of Plans",
  "12 Sets of Plans",
  "Reproducible",
  "CAD Files",
  "Mirror Reverse",
  "Material List",
  "Opt. Crawl Found.",
  "Right Reading Reverse",
  "Additional Set of Plans",
  "Opt. Basement Found.",
  "Color Rendering",
  "Reuse Fees",
  "Opt. Slab Found.",
] as const;

/** Default room rows from Exhibit C room schedule. */
export function defaultPublisherRoomSchedule(): PublisherIntakeRoomRow[] {
  const names = [
    "Bath 2",
    "Bath 3",
    "Bath 4",
    "Bath 5",
    "Bath 6",
    "Bedroom 2",
    "Bedroom 3",
    "Bedroom 4",
    "Bedroom 5",
    "Bedroom 6",
    "Bonus Room",
    "Breakfast",
    "Coat Closet",
    "Computer Room",
    "Deck",
    "Den",
    "Dining Room",
    "Family Room",
    "Foyer",
    "Front Porch",
    "Game Room",
    "Garage",
    "Great Room",
    "Hall",
    "Home Office",
    "Keeping Room",
    "Kitchen",
    "Laundry",
    "Library",
    "Linen Closet",
    "Living Room",
    "Loft",
    "Master Bath",
    "Master Suite",
    "Master Closet 2",
    "Master Sitting",
    "Media Room",
    "Mud Room",
    "Office",
    "Pantry",
    "Port Cochere",
    "Powder Room",
    "Rear Porch",
    "Screened Porch",
    "Study",
    "Sunroom",
    "Toilet Room",
  ];
  return names.map((name, index) => ({
    id: `room-${index}`,
    name,
    width: "",
    depth: "",
    ceilingHeight: "",
    ceilingType: "",
  }));
}

export function emptyPublisherIntakeForm(): import("./types").PublisherIntakeForm {
  return {
    designerName: "",
    designerPlanNumber: "",
    designerPlanName: "",
    formDate: "",
    abhpNumber: "",
    planType: "",
    numberOfStories: "",
    numberOfBedrooms: "",
    numberOfFullBaths: "",
    numberOfHalfBaths: "",
    garageTypes: [],
    garageStalls: "",
    mainRoofPitch: "",
    sqftFirstFloor: "",
    sqftSecondFloor: "",
    sqftThirdFloor: "",
    sqftBasement: "",
    sqftGarage: "",
    sqftBonusRoom: "",
    sqftTotalHeated: "",
    widthFeetInches: "",
    depthFeetInches: "",
    heightFeetInches: "",
    porchTypes: [],
    foundations: [],
    architecturalStyles: [],
    otherSuggestedStyles: "",
    planFeatures: [],
    houseDescription: "",
    rooms: defaultPublisherRoomSchedule(),
    planProductsPricing: Object.fromEntries(
      PUBLISHER_PLAN_PRODUCTS.map((p) => [p, ""]),
    ),
    cadFileFormats: "",
  };
}
