import type { TileDef } from "./types";
// Package-resident tiles (moved in Track C Phase 3) — named exports.
import {
  IntakeQueueTile,
  IntakeTile,
  MapTile,
  TopographyTile,
  DrainageTile,
  HydrologyTile,
  SubsurfaceTile,
  PropertyBriefTile,
  HazardProfileTile,
  EncumbranceTile,
  SheetExtractionTile,
  ResponseTasksTile,
} from "@hauska/cortex-tiles";
// Option-3 app-resident tiles (kept in the app; still error-boundary-wrapped).
import ComplianceRunTile from "../tiles/Compliance/compliance-run";
import DocumentViewerTile from "../tiles/Compliance/document-viewer";
import LetterTile from "../tiles/Deliverable/letter";
import { makeStubTile, type StubTileMeta } from "../tiles/stubFactory";

type TileMeta = Omit<TileDef, "el"> & { component: () => React.ReactElement };

function stub(meta: StubTileMeta): () => React.ReactElement {
  return makeStubTile(meta);
}

const TILE_META: TileMeta[] = [
  // Compliance
  {
    id: "intake",
    label: "Intake & Upload",
    category: "Compliance",
    engine: "engagement",
    status: "live",
    requires: { engagementId: false },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["create_engagement", "upload_document", "parse_intake"],
    component: () => <IntakeTile />,
  },
  {
    id: "intake-queue",
    label: "Intake & Queue",
    category: "Compliance",
    engine: "engagement",
    status: "live",
    requires: {},
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["get_queue"],
    component: () => <IntakeQueueTile />,
  },
  {
    id: "compliance-run",
    label: "Compliance Run",
    category: "Compliance",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true, uploadedDocuments: true },
    produces: { findings: true, spatialOverlays: true },
    modes: ["full", "card", "raw"],
    mcpTools: ["run_compliance_pass", "get_compliance_findings"],
    component: () => <ComplianceRunTile />,
  },
  {
    id: "document-viewer",
    label: "Document Viewer",
    category: "Compliance",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true, uploadedDocuments: true },
    produces: { annotations: true },
    modes: ["full"],
    mcpTools: [],
    component: () => <DocumentViewerTile />,
  },
  {
    id: "findings-library",
    label: "Findings Library",
    category: "Compliance",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true },
    produces: { findings: true },
    modes: ["full", "card", "raw"],
    mcpTools: ["get_compliance_findings"],
    component: stub({ id: "findings-library", label: "Findings Library", category: "Compliance", status: "live" }),
  },
  {
    id: "calibration",
    label: "Finding Calibration",
    category: "Compliance",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true, completedFindings: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["get_calibration_report"],
    component: stub({ id: "calibration", label: "Finding Calibration", category: "Compliance", status: "live" }),
  },
  {
    id: "precedence",
    label: "Precedence Engine",
    category: "Compliance",
    engine: "code",
    status: "degraded",
    degradedReason: "Production gate not activated; most-stringent-governs logic built but disabled in production.",
    requires: { jurisdiction: true },
    produces: {},
    modes: ["full", "raw"],
    mcpTools: ["get_precedence"],
    component: stub({ id: "precedence", label: "Precedence Engine", category: "Compliance", status: "degraded", degradedReason: "Production gate not activated; most-stringent-governs logic built but disabled in production." }),
  },
  {
    id: "icc-ingest",
    label: "ICC Code Connect Ingest",
    category: "Compliance",
    engine: "code",
    status: "partial",
    degradedReason: "Credentials live; API contract not verified.",
    requires: { jurisdiction: true },
    produces: {},
    modes: ["full", "raw"],
    mcpTools: [],
    component: stub({ id: "icc-ingest", label: "ICC Code Connect Ingest", category: "Compliance", status: "partial", degradedReason: "Credentials live; API contract not verified." }),
  },
  {
    id: "ahj-precedent",
    label: "Permit AHJ Precedent",
    category: "Compliance",
    status: "planned",
    requires: { jurisdiction: true },
    produces: {},
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "ahj-precedent", label: "Permit AHJ Precedent", category: "Compliance", status: "planned" }),
  },
  {
    id: "code-broadcast",
    label: "Code Change Broadcast",
    category: "Compliance",
    status: "planned",
    requires: { jurisdiction: true },
    produces: {},
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "code-broadcast", label: "Code Change Broadcast", category: "Compliance", status: "planned" }),
  },
  // Site Analysis
  {
    id: "topography",
    label: "Topography",
    category: "Site Analysis",
    engine: "spatial",
    status: "live",
    requires: { engagementId: true },
    produces: { spatialOverlays: true },
    modes: ["full", "card", "raw"],
    mcpTools: ["get_topography"],
    component: () => <TopographyTile />,
  },
  {
    id: "drainage",
    label: "Drainage",
    category: "Site Analysis",
    engine: "spatial",
    status: "live",
    requires: { engagementId: true },
    produces: { spatialOverlays: true },
    modes: ["full", "card", "raw"],
    mcpTools: ["get_drainage"],
    component: () => <DrainageTile />,
  },
  {
    id: "hydrology",
    label: "Hydrology",
    category: "Site Analysis",
    engine: "spatial",
    status: "degraded",
    degradedReason: "pysheds not installed in Cloud Run worker.",
    requires: { engagementId: true },
    produces: { spatialOverlays: true },
    modes: ["full", "card", "raw"],
    mcpTools: ["get_hydrology"],
    component: () => <HydrologyTile />,
  },
  {
    id: "subsurface",
    label: "Subsurface Suitability",
    category: "Site Analysis",
    engine: "spatial",
    status: "partial",
    degradedReason: "SSURGO ECONNRESET — USDA TLS issue.",
    requires: { engagementId: true },
    produces: { spatialOverlays: true },
    modes: ["full", "card", "raw"],
    mcpTools: ["get_subsurface"],
    component: () => <SubsurfaceTile />,
  },
  {
    id: "stormwater",
    label: "Stormwater / Detention",
    category: "Site Analysis",
    status: "planned",
    requires: { engagementId: true },
    produces: { spatialOverlays: true },
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "stormwater", label: "Stormwater / Detention", category: "Site Analysis", status: "planned" }),
  },
  {
    id: "cut-fill",
    label: "Grading / Cut-Fill",
    category: "Site Analysis",
    status: "planned",
    requires: { engagementId: true },
    produces: { spatialOverlays: true },
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "cut-fill", label: "Grading / Cut-Fill", category: "Site Analysis", status: "planned" }),
  },
  {
    id: "solar",
    label: "Solar / Aspect",
    category: "Site Analysis",
    status: "planned",
    requires: { engagementId: true },
    produces: { spatialOverlays: true },
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "solar", label: "Solar / Aspect", category: "Site Analysis", status: "planned" }),
  },
  {
    id: "viewshed",
    label: "Viewshed",
    category: "Site Analysis",
    status: "planned",
    requires: { engagementId: true },
    produces: { spatialOverlays: true },
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "viewshed", label: "Viewshed", category: "Site Analysis", status: "planned" }),
  },
  {
    id: "map",
    label: "Map",
    category: "Site Analysis",
    engine: "spatial",
    status: "live",
    minColShare: 0.3,
    requires: {},
    produces: { spatialOverlays: true },
    modes: ["full", "raw"],
    mcpTools: [],
    component: () => <MapTile />,
  },
  // Property Intel
  {
    id: "property-brief",
    label: "Property Brief",
    category: "Property Intel",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true, apn: true },
    produces: {},
    modes: ["full", "card", "inline", "raw"],
    mcpTools: ["get_property_brief"],
    component: () => <PropertyBriefTile />,
  },
  {
    id: "hazard",
    label: "Hazard Profile",
    category: "Property Intel",
    engine: "spatial",
    status: "live",
    requires: { engagementId: true, apn: true },
    produces: { spatialOverlays: true },
    modes: ["full", "card", "inline", "raw"],
    mcpTools: ["get_hazard_profile"],
    component: () => <HazardProfileTile />,
  },
  {
    id: "place-dossier",
    label: "Place Dossier",
    category: "Property Intel",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["get_place_dossier"],
    component: stub({ id: "place-dossier", label: "Place Dossier", category: "Property Intel", status: "live" }),
  },
  {
    id: "encumbrances",
    label: "Encumbrance Report",
    category: "Property Intel",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true, apn: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["get_encumbrances"],
    component: () => <EncumbranceTile />,
  },
  {
    id: "setbacks",
    label: "Local Setbacks",
    category: "Property Intel",
    engine: "code",
    status: "live",
    requires: { apn: true, jurisdiction: true },
    produces: {},
    modes: ["full", "card", "inline", "raw"],
    mcpTools: ["get_setbacks"],
    component: stub({ id: "setbacks", label: "Local Setbacks", category: "Property Intel", status: "live" }),
  },
  {
    id: "climate-risk",
    label: "Climate Risk Trajectory",
    category: "Property Intel",
    status: "planned",
    requires: { apn: true },
    produces: {},
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "climate-risk", label: "Climate Risk Trajectory", category: "Property Intel", status: "planned" }),
  },
  {
    id: "insurance-estimate",
    label: "Insurance Cost Estimate",
    category: "Property Intel",
    status: "planned",
    requires: { apn: true },
    produces: {},
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "insurance-estimate", label: "Insurance Cost Estimate", category: "Property Intel", status: "planned" }),
  },
  {
    id: "jurisdiction-rank",
    label: "Jurisdiction Comparison",
    category: "Property Intel",
    status: "planned",
    requires: { jurisdiction: true },
    produces: {},
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "jurisdiction-rank", label: "Jurisdiction Comparison", category: "Property Intel", status: "planned" }),
  },
  // Design Accelerator
  {
    id: "sheet-extraction",
    label: "Sheet Extraction",
    category: "Design Accelerator",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true, uploadedDocuments: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["extract_sheets", "get_sheets"],
    component: () => <SheetExtractionTile />,
  },
  {
    id: "doc-parsing",
    label: "Document Parsing",
    category: "Design Accelerator",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true, uploadedDocuments: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["parse_document"],
    component: stub({ id: "doc-parsing", label: "Document Parsing", category: "Design Accelerator", status: "live" }),
  },
  {
    id: "product-spec",
    label: "Product Spec Reference",
    category: "Design Accelerator",
    engine: "code",
    status: "live",
    requires: {},
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["get_product_spec"],
    component: stub({ id: "product-spec", label: "Product Spec Reference", category: "Design Accelerator", status: "live" }),
  },
  {
    id: "detail-callouts",
    label: "Detail Callout Specs",
    category: "Design Accelerator",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["get_detail_callouts"],
    component: stub({ id: "detail-callouts", label: "Detail Callout Specs", category: "Design Accelerator", status: "live" }),
  },
  {
    id: "response-tasks",
    label: "Response Tasks",
    category: "Design Accelerator",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true, completedFindings: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["get_response_tasks"],
    component: () => <ResponseTasksTile />,
  },
  {
    id: "bim-query",
    label: "BIM Model Query",
    category: "Design Accelerator",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["query_bim_model"],
    component: stub({ id: "bim-query", label: "BIM Model Query", category: "Design Accelerator", status: "live" }),
  },
  {
    id: "ifc-ingest",
    label: "IFC Ingest",
    category: "Design Accelerator",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true, uploadedDocuments: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["ingest_ifc"],
    component: stub({ id: "ifc-ingest", label: "IFC Ingest", category: "Design Accelerator", status: "live" }),
  },
  {
    id: "engagement-match",
    label: "Engagement Match (Revit)",
    category: "Design Accelerator",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["match_engagement"],
    component: stub({ id: "engagement-match", label: "Engagement Match (Revit)", category: "Design Accelerator", status: "live" }),
  },
  {
    id: "renders",
    label: "Renders",
    category: "Design Accelerator",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["generate_render"],
    component: stub({ id: "renders", label: "Renders", category: "Design Accelerator", status: "live" }),
  },
  {
    id: "collateral-export",
    label: "Collateral Export",
    category: "Design Accelerator",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["export_collateral"],
    component: stub({ id: "collateral-export", label: "Collateral Export", category: "Design Accelerator", status: "live" }),
  },
  // Deliverable
  {
    id: "letter",
    label: "Deliverable Letter",
    category: "Deliverable",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true, completedFindings: true },
    produces: { letter: true },
    modes: ["full", "card", "raw"],
    mcpTools: ["generate_letter"],
    component: () => <LetterTile />,
  },
  {
    id: "letter-render",
    label: "Letter Render",
    category: "Deliverable",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true, completedFindings: true },
    produces: { letter: true },
    modes: ["full", "card", "raw"],
    mcpTools: ["render_letter"],
    component: stub({ id: "letter-render", label: "Letter Render", category: "Deliverable", status: "live" }),
  },
  {
    id: "letter-send",
    label: "Letter Send",
    category: "Deliverable",
    engine: "engagement",
    status: "live",
    requires: { engagementId: true, completedFindings: true },
    produces: { letter: true },
    modes: ["full", "card", "raw"],
    mcpTools: ["send_letter"],
    component: stub({ id: "letter-send", label: "Letter Send", category: "Deliverable", status: "live" }),
  },
  // Market
  {
    id: "avm",
    label: "AVM / Valuation",
    category: "Market",
    engine: "engagement",
    status: "partial",
    degradedReason: "Cotality AVM keys present; not fully wired.",
    requires: { apn: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["get_avm"],
    component: stub({ id: "avm", label: "AVM / Valuation", category: "Market", status: "partial", degradedReason: "Cotality AVM keys present; not fully wired." }),
  },
  {
    id: "rent-comps",
    label: "Rent / Comps",
    category: "Market",
    engine: "engagement",
    status: "partial",
    degradedReason: "Cotality demo quota: 100 req/day, expires ~2026-07-06.",
    requires: { apn: true },
    produces: {},
    modes: ["full", "card", "raw"],
    mcpTools: ["get_rent_comps"],
    component: stub({ id: "rent-comps", label: "Rent / Comps", category: "Market", status: "partial", degradedReason: "Cotality demo quota: 100 req/day, expires ~2026-07-06." }),
  },
  {
    id: "pro-forma",
    label: "Cash-Flow Pro Forma",
    category: "Market",
    status: "planned",
    requires: { apn: true },
    produces: {},
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "pro-forma", label: "Cash-Flow Pro Forma", category: "Market", status: "planned" }),
  },
  {
    id: "deal-score",
    label: "Deal Score",
    category: "Market",
    status: "planned",
    requires: { apn: true },
    produces: {},
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "deal-score", label: "Deal Score", category: "Market", status: "planned" }),
  },
  {
    id: "motivated-seller",
    label: "Motivated Seller Heat",
    category: "Market",
    status: "planned",
    requires: { apn: true },
    produces: { spatialOverlays: true },
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "motivated-seller", label: "Motivated Seller Heat", category: "Market", status: "planned" }),
  },
  {
    id: "rehab-opportunity",
    label: "Rehab Opportunity",
    category: "Market",
    status: "planned",
    requires: { apn: true },
    produces: {},
    modes: ["full"],
    mcpTools: [],
    component: stub({ id: "rehab-opportunity", label: "Rehab Opportunity", category: "Market", status: "planned" }),
  },
];

export const TILE_REGISTRY: Record<string, TileDef> = Object.fromEntries(
  TILE_META.map(({ component, ...meta }) => [
    meta.id,
    { ...meta, el: component },
  ]),
);

export const ALL_TILES: TileDef[] = TILE_META.map(({ component, ...meta }) => ({
  ...meta,
  el: component,
}));

export const TILE_CATEGORIES = [
  "Compliance",
  "Site Analysis",
  "Property Intel",
  "Design Accelerator",
  "Deliverable",
  "Market",
] as const;

export function getTile(id: string): TileDef | undefined {
  return TILE_REGISTRY[id];
}
