import { StyleProbeThemePicker } from "@workspace/portal-ui";

export default function StyleProbe() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-['Oxygen'] font-bold text-[var(--text-primary)]">
          Style Probe
        </h1>
        <p className="sc-body mt-1">
          Compare chrome variants below. Colored pills stay semantic across themes.
        </p>
      </div>

      <StyleProbeThemePicker />

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="sc-card p-4">
          <div className="sc-label">Active Engagements</div>
          <div className="sc-kpi-md mt-2">7</div>
          <div className="sc-body mt-1">Across 3 jurisdictions</div>
        </div>
        <div className="sc-card sc-accent-cyan p-4">
          <div className="sc-label">AI Findings Today</div>
          <div className="sc-kpi-md mt-2">12</div>
          <div className="sc-body mt-1">Generated by Claude</div>
        </div>
        <div className="sc-card sc-accent-red p-4">
          <div className="sc-label">Blocking</div>
          <div className="sc-kpi-md mt-2">3</div>
          <div className="sc-body mt-1">Submittals rejected</div>
        </div>
      </div>

      <div className="flex gap-2 flex-wrap">
        <span className="sc-pill sc-pill-green">Approved</span>
        <span className="sc-pill sc-pill-amber">Needs review</span>
        <span className="sc-pill sc-pill-red">Blocking</span>
        <span className="sc-pill sc-pill-cyan">AI generated</span>
        <span className="sc-pill sc-pill-blue">Info</span>
        <span className="sc-pill sc-pill-muted">Draft</span>
      </div>

      <div className="flex gap-2 flex-wrap">
        <button type="button" className="sc-btn-primary">
          Submit design
        </button>
        <button type="button" className="sc-btn-ghost">
          View comments
        </button>
        <button type="button" className="sc-btn-alert">
          Reject
        </button>
      </div>

      <div className="sc-card">
        <div className="sc-card-header sc-row-sb">
          <span className="sc-label">Finding · Seguin Residence — A2.04</span>
          <span className="sc-pill sc-pill-red">Blocking</span>
        </div>
        <div className="alert-block critical">
          <div className="sc-medium">Egress door swing direction</div>
          <div className="sc-body mt-1">
            Door at corridor C-104 swings against egress travel.
            <span className="sc-ref ml-1">IBC §1010.1.2</span>
          </div>
        </div>
        <div className="sc-card-footer sc-row-sb">
          <span className="sc-meta">Identified by Claude · 2 min ago</span>
          <button type="button" className="sc-btn-sm">
            View on plan
          </button>
        </div>
      </div>
    </div>
  );
}
